language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 src/
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

branches:
  except:
    - sculpin
    - gh-pages
